AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  bucketName:
    Type: String
    Description: "Bucket Name"
Resources:
  s3Demo:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketName
        
