---
 - hsots: web
   user: ansible1
   become: true
   tasks:
     -  name: :creating new user:
        user:
          name: Install
          comment: new user
     -  name: "Install docker"
        yum: 
          name: docker
          state: present
     -  name: install the latest version of Python-pip
        yum:
          name: python-pip
          state: latest
     -  name: install the latest version of Docker-compose from pip
          pip:
            name: docker-compose
     -  name: "Start docker services"
        service:
          name: docker
          state: started
     -  name: "Install maven"
        yum: 
          name : maven
          state: present
